# Generated by Django 4.0.4 on 2022-06-05 13:17

import contextlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_alter_actor_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_image',
            field=models.ImageField(default=contextlib.nullcontext, upload_to='actor'),
        ),
    ]
