# Generated by Django 4.0.4 on 2022-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_alter_actor_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='actor'),
        ),
    ]
