# Generated by Django 4.0.4 on 2022-06-04 21:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='director Name')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Movie Name')),
                ('production_year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), movie.models.max_value_current_year])),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(to='actor.actor')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.director')),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
